In [4]:
import pandas as pd
import seaborn as sns

In [5]:
p_df = sns.load_dataset('penguins')

In [6]:
p_df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [7]:
p_df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

## dropping nas

In [8]:
p_df = p_df.dropna()

## dropping duplicates

In [9]:
p_df = p_df.drop_duplicates()

## X-y split

In [11]:
X= p_df[['flipper_length_mm', 'bill_depth_mm']]
y = p_df[['body_mass_g']]

## Train-test split

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split( X,y, random_state=42)#

In [45]:
y_test

body_mass_g
0        3250.0
1        4875.0
2        4000.0
3        3675.0
4        4050.0
..          ...
79       5650.0
80       3450.0
81       4250.0
82       3200.0
83       3700.0

[84 rows x 1 columns]

## Model training

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [71]:
model.coef_

array([[52.20343571, 13.10815533]])

In [49]:
model.intercept_

array([-6509.21617362])

## Predict mass of random penguin

In [50]:
random_penguin = X_test.sample()

In [62]:
random_penguin

flipper_length_mm  bill_depth_mm
328              208.0           14.0

In [63]:
model.predict(random_penguin)

array([[4532.61262802]])

## Create predictions for the test set

In [64]:
y_pred = model.predict(X_test)

In [65]:
y_pred= pd.DataFrame(y_pred)

In [66]:
y_test = y_test.reset_index(drop=True)

In [67]:
residuals_df= pd.concat([y_test, y_pred], axis=1)

In [68]:
residuals_df= residuals_df.rename(columns= {"body_mass_g": "y_test", 0: "y_pred"})

In [69]:
residuals_df["residual"] = residuals_df["y_test"]- residuals_df["y_pred"]

In [70]:
residuals_df.head()

y_test       y_pred    residual
0  3250.0  3001.901576  248.098424
1  4875.0  5271.325621 -396.325621
2  4000.0  3920.819556   79.180444
3  3675.0  4053.835184 -378.835184
4  4050.0  3752.411909  297.588091

## Calculating metrics

In [72]:
mean_error = residuals_df["residual"].mean()

In [73]:
mean_error

0.4256712769165244

In [80]:
from sklearn.metrics import mean_squared_error as mse, mean_absolute_error as mae

In [79]:
mse(y_test, y_pred)

135012.91730727023

In [76]:
mae(y_test, y_pred)

295.2392937185123

In [81]:
rmse= mse( y_test, y_pred, squared = False)# either

In [82]:
rmse

367.44103922571065

In [77]:
import numpy as np
np.sqrt(mse(y_test, y_pred)) #or this

367.44103922571065